export const GET_LOCATION_BEGIN = "GET_LOCATION_BEGIN";
export const GET_LOCATION_SUCCESS = "GET_LOCATION_SUCCESS";
export const GET_LOCATION_FAILURE = "GET_LOCATION_FAILURE";
export const ADD_NEW_VISITED_SUCCESS = "ADD_NEW_VISITED_SUCCESS";
export const CLEAR_LOCATION = "CLEAR_LOCATION";
export const DELETE_VISITED_LOCATION = "DELETE_VISITED_LOCATION";

export const START_SEARCHING = "START_SEARCHING";
export const STOP_SEARCHING = "STOP_SEARCHING";

export const GET_CURRENT_POSITION_BEGIN = "GET_CURRENT_POSITION_BEGIN";
export const GET_CURRENT_POSITION_SUCCESS = "GET_CURRENT_POSITION_SUCCESS";
export const GET_CURRENT_POSITION_FAILURE = "GET_CURRENT_POSITION_FAILURE";

export const ADD_FAVORITE_LOCATION = "ADD_FAVORITE_LOCATION";
export const DELETE_FAVORITE_LOCATION = "DELETE_FAVORITE_LOCATION";

export const ADD_RECENT_LOCATION = "ADD_RECENT_LOCATION";
export const DELETE_RECENT_LOCATION = "DELETE_RECENT_LOCATION";

export const FETCH_FORECAST_BEGIN = "FETCH_FORECAST_BEGIN";
export const FETCH_FORECAST_SUCCESS = "FETCH_FORECAST_SUCCESS";
export const FETCH_FORECAST_FAILURE = "FETCH_FORECAST_FAILURE";
export const DELETE_FORECAST_FOR_LOCATION = "DELETE_FORECAST_FOR_LOCATION";

export const MAP_LOAD_BEGIN = "MAP_LOAD_BEGIN";
export const MAP_LOAD_SUCCESS = "MAP_LOAD_SUCCESS";

export const CHANGE_UNITS = "CHANGE_UNITS";
